bin/imgur: Swap imgur scripts

diff --git a/bin/imgur b/bin/imgur
--- a/bin/imgur
+++ b/bin/imgur
@@ -1,115 +1,142 @@
 #!/bin/bash
-
-# imgur script by Bart Nagel <bart@tremby.net>
-# version 4
-# I release this into the public domain. Do with it what you will.
-
-# Required: curl
+# Copyright (c) 2016 Phillip Tang <tangphillip@gmail.com>
+# 
+# Permission is hereby granted, free of charge, to any person obtaining a
+# copy of this software and associated documentation files (the "Software"),
+# to deal in the Software without restriction, including without limitation
+# the rights to use, copy, modify, merge, publish, distribute, sublicense,
+# and/or sell copies of the Software, and to permit persons to whom the
+# Software is furnished to do so, subject to the following conditions:
 #
-# Optional: xsel or xclip for automatically putting the URLs on the X selection 
-# for easy pasting
+# The above copyright notice and this permission notice shall be included
+# in all copies or substantial portions of the Software.
 #
-# Instructions:
-# Put it somewhere in your path and maybe rename it:
-# 	mv ~/Downloads/imgurbash.sh ~/bin/imgur
-# Make it executable:
-# 	chmod +x ~/bin/imgur
-# Optional, since Alan kindly provided an API key for this script: stick your 
-# API key in the top:
-# 	vim ~/bin/imgur
-# Upload an image:
-# 	imgur images/hilarious/manfallingover.jpg
-# Upload multiple images:
-# 	imgur images/delicious/cake.png images/exciting/bungeejump.jpg
-# The URLs will be displayed (and the delete page's URLs will be displayed on 
-# stderr). If you have xsel or xclip the URLs will also be put on the X 
-# selection, which you can usually paste with a middle click.
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
+# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
+# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
+# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
+# DEALINGS IN THE SOFTWARE.
 
-# API Key provided by Alan@imgur.com
-apikey="b3625162d3418ac51a9ee805b1840452"
+
+# Based the work of Bart Nagel <bart@tremby.net>
+# If you have rate limit issues, get your own key at http://api.imgur.com/
+CLIENT_ID="9657b96ca0b7f38"
+CLIPBOARD=true
 
 # function to output usage instructions
 function usage {
-echo "Usage: $(basename $0) <filename> [<filename> [...]]" >&2
-echo "Upload images to imgur and output their new URLs to stdout. Each one's" >&2
-echo "delete page is output to stderr between the view URLs." >&2
-echo "If xsel or xclip is available, the URLs are put on the X selection for" >&2
-echo "easy pasting." >&2
+	echo "Usage: $(basename "$0") [filenames]
+Upload images to imgur, print their URLs to stdout, and print the delete pages URL to stderr.
+If you're on a Mac or have xsel/xclip, copy the images URLs to the clipboard.
+If you don't especify any filename, they will be read from standard input." >&2
+}
+
+function upload_image {
+	# the "Expect: " header is to get around a problem when using this through the
+	# Squid proxy. Not sure if it's a Squid bug or what.
+	curl \
+		-H "Authorization: Client-ID $CLIENT_ID" \
+		-H "Expect: " \
+		-F "image=@$1" \
+		https://api.imgur.com/3/image 2>/dev/null
+}
+
+function parse_url_from_response {
+	echo "$1" | sed -E 's/.*"link":"([^"]+)".*/\1/' | sed "s|\\\\/|/|g"
+}
+
+function parse_delete_url_from_response {
+	echo "$1" | sed -E 's/.*"deletehash":"([^"]+)".*/\1/' | sed "s|^|http://imgur.com/delete/|"
 }
 
 # check API key has been entered
-if [ "$apikey" = "Your API key" ]; then
-  echo "You first need to edit the script and put your API key in the variable near the top." >&2
-  exit 15
+if [ "$CLIENT_ID" = "Your Client ID" ]; then
+	echo "You first need to edit the script and put your API key in the variable near the top." >&2
+	exit 15
 fi
 
 # check arguments
-if [ "$1" = "-h" -o "$1" = "--help" ]; then
-  usage
-  exit 0
-elif [ $# == 0 ]; then
-  echo "No file specified" >&2
-  usage
-  exit 16
+if [[ "$1" == "-h" || "$1" == "--help" ]]; then
+	usage
+	exit 0
+elif [[ "$1" == "-x" || "$1" == "--no-clipboard" ]]; then
+	CLIPBOARD=false
+	shift
 fi
 
 # check curl is available
-type curl >/dev/null 2>/dev/null || {
-echo "Couln't find curl, which is required." >&2
-exit 17
+which curl &>/dev/null || {
+	echo "Couln't find curl, which is required." >&2
+	exit 17
 }
 
-clip=""
-errors=false
+# get list of files either from arguments or standard input
+files_to_upload=""
 
-# loop through arguments
-while [ $# -gt 0 ]; do
-  file="$1"
-  shift
-
-  # check file exists
-  if [ ! -f "$file" ]; then
-    echo "file '$file' doesn't exist, skipping" >&2
-    errors=true
-    continue
-  fi
-
-  # upload the image
-  response=$(curl -F "key=$apikey" -H "Expect: " -F "image=@$file" \
-    http://imgur.com/api/upload.xml 2>/dev/null)
-  # the "Expect: " header is to get around a problem when using this through 
-  # the Squid proxy. Not sure if it's a Squid bug or what.
-  if [ $? -ne 0 ]; then
-    echo "Upload failed" >&2
-    errors=true
-    continue
-  elif [ $(echo $response | grep -c "<error_msg>") -gt 0 ]; then
-    echo "Error message from imgur:" >&2
-    echo $response | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
-    errors=true
-    continue
-  fi
-
-  # parse the response and output our stuff
-  url=$(echo $response | sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/')
-  deleteurl=$(echo $response | sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/')
-  echo $url
-  echo "Delete page: $deleteurl" >&2
-
-  # append the URL to a string so we can put them all on the clipboard later
-  clip="$clip$url
-  "
-done
-
-# put the URLs on the clipboard if we have xsel or xclip
-if [ $DISPLAY ]; then
-  { type xclip >/dev/null 2>/dev/null && echo -n $clip | xclip -selection clipboard; } \
-    || { type xsel >/dev/null 2>/dev/null && echo -n $clip | xsel; } \
-    || echo "Haven't copied to the clipboard: no xsel or xclip" >&2
+if [[ $# -gt 0 ]]; then
+	while [[ $# -gt 0 ]]; do
+		if [ -z "$files_to_upload" ]; then
+			files_to_upload="$1"
+		else
+			files_to_upload="$files_to_upload"$'\n'"$1"
+		fi
+		shift
+	done
 else
-  echo "Haven't copied to the clipboard: no \$DISPLAY" >&2
+	# I know, I know...
+	files_to_upload=$(cat)
 fi
 
-if $errors; then
-  exit 1
+
+# handle filenames with spaces gracefully
+# sadly, it will croak when a filename has a newline
+# then again, it's kinda users fault on that case
+ifs_old=$IFS
+IFS=$'\n'
+
+# upload the images one at a time
+list_urls=""
+for file in $files_to_upload; do
+	response=$(upload_image "$file" "$CLIENT_ID")
+
+	# verify the upload
+	# this stops the batch operation, which seems the best course of action
+	# since the script has such detailed error levels
+	if [ $? -ne 0 ]; then
+		echo "Upload failed" >&2
+		exit 2
+	elif [ "$(echo "$response" | grep -c "<error_msg>")" -gt 0 ]; then
+		echo "Error message from imgur:" >&2
+		echo "$response" | sed -E 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
+		exit 3
+	elif [[ "$response" != *deletehash* ]]; then
+		echo "Unknown Failure: Imgur is probably down for maintenance."
+		exit 4
+	fi
+
+	# parse the response and output our stuff
+	url=$(parse_url_from_response "$response")
+	deleteurl=$(parse_delete_url_from_response "$response")
+
+	# add the url to the list for later clipboard manipulation
+	# avoid adding a trailing newline at the end
+	if [ -z "$list_urls" ]; then
+		list_urls="$url"
+	else
+		list_urls="$list_urls"$'\n'"$url"
+	fi
+
+	echo "$url"
+	echo "Delete page: $deleteurl" >&2
+done
+IFS=$ifs_old
+
+# put the URL on the clipboard if we have xsel or xclip
+if [ $CLIPBOARD == true ]; then
+	{ which pbcopy &>/dev/null && echo -n "$list_urls" | pbcopy; } \
+		|| { which xsel &>/dev/null && echo -n "$list_urls" | xsel --input --clipboard; } \
+		|| { which xclip &>/dev/null && echo -n "$list_urls" | xclip -selection clipboard; } \
+		|| echo "Haven't copied to the clipboard: no pbcopy, xsel, or xclip" >&2
 fi
